#!/bin/bash

# ##################################################
#
# HISTORY:
#
# 20160609 - v0.0.1  - Restart, Clean Slate
# 20170622 - v0.0.2  - Update Readme and user directory
#
# ##################################################

args=("$@")

#main_lookup no options just single argument
function main_lookup {

    if [ ! -f /Users/jvirgen/countdown.txt ]; then
        echo "Countdown File newly created"
        touch /Users/jvirgen/countdown.txt
    fi

    file="/Users/jvirgen/countdown.txt"

    while IFS=, read -r name event; do
        if [ "$name" = ${args[0]} ]; then
            count=$(( ($(gdate --date="$event" +%s) - $(gdate +%s) )/(60*60*24) ))
            reset=`tput sgr0`

            if [ $count -lt 30 ]; then
                color=`tput setaf 1`
            elif [ $count -lt 60 ]; then
                color=`tput setaf 3`
            elif [ $count -lt 100 ]; then
                color=`tput setaf 6`
            else
                color=`tput setaf 2`
            fi

            if [ $count -lt 0 ]; then
                echo "${color}${count#-}${reset} Days have passed since ${args}"
            else
                echo "There are ${color}${count}${reset} Days until ${args}"
            fi
        fi
    done <$file

}

#add event function
function add_event {

  if [ ! -f /Users/jvirgen/countdown.txt ]; then
      echo "Countdown File newly created"
      touch /Users/jvirgen/countdown.txt
  fi

  echo $OPTARG >> "/Users/jvirgen/countdown.txt"
  sed -i '' -n p "/Users/jvirgen/countdown.txt"
  echo "added " ${args[1]}

  exit 1
}

#delete event function
function delete_event {

  sed "/$OPTARG/d" "/Users/jvirgen/countdown.txt" > "/Users/jvirgen/countdown.temp" ; mv "/Users/jvirgen/countdown.temp" "/Users/jvirgen/countdown.txt"
  echo "deleted " $OPTARG

  exit 1
}

#lookup event function
function list_events {

  if [ ! -f /Users/jvirgen/countdown.txt ]; then
      echo "Countdown File newly created"
      touch /Users/jvirgen/countdown.txt
  fi

  sort -t"," -k2,2 "/Users/jvirgen/countdown.txt" > "/Users/jvirgen/countdown.temp"

  file="/Users/jvirgen/countdown.temp"

  while IFS=, read -r name event; do
    count=$(( ($(gdate --date="$event" +%s) - $(gdate +%s) )/(60*60*24) ))
    reset=`tput sgr0`

    if [ $count -lt 30 ]; then
        color=`tput setaf 1`
    elif [ $count -lt 60 ]; then
        color=`tput setaf 3`
    elif [ $count -lt 100 ]; then
        color=`tput setaf 6`
    else
        color=`tput setaf 2`
    fi

    echo "$name" ${color} "$count" ${reset}
  done <$file

  rm "/Users/jvirgen/countdown.temp"

  exit 1
}

while getopts "a:d:l" opt; do
  case $opt in
    a)
      add_event
      ;;
    d)
      delete_event
      ;;
    l)
      list_events
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# catch if no flag or parameter is passed
if [ $# -eq 0 ]; then
    list_events
    exit 1
fi

main_lookup